### ISSUE TITLE
restore course files

### ISSUE THREAD

**Issue by arjanvandervelde** [GSBS-Bootstrappers/bootstrappers-courses#11]
course files seems to have disappeared. see http://bioinfo.umassmed.edu/bootstrappers/bootstrappers-courses/python1/Python_I/Session%20IV.html

**Comment by crmackay** [comment]
the pdfs and .ipynbs are there...I can't find the html files anywhere in repo...were they made from the notebooks directly on the bib server? maybe they never got committed back to github?

**Comment by nickjhathaway** [comment]
course files that are converted from ipython notebooks or rmakrdown documents aren't checked in since these are updated whenever the original files are updated so it would be like checking in changes twice.  I have put scripts in bin that will convert these to the html needed and in within the courses themselves there are scripts to convert all needed pages.  The site has been updated to point the docker-site and these pages have been created.
